source(file.path(getwd(), 'R/tests/test-table.R'))
source(file.path(getwd(), 'R/tests/data-frame-access.R'))
source(file.path(getwd(), 'R/tests/mutation.R'))
source(file.path(getwd(), 'R/tests/constants.R'))
source(file.path(getwd(), 'R/tests/test-function.R'))

testTransformationForTable()
testDataFrameAccess()
testMutation()
testConstants()
testDefineFunction()