source(file.path(getwd(), 'R/tests/test-table.R'))
source(file.path(getwd(), 'R/tests/data-frame-access.R'))
source(file.path(getwd(), 'R/tests/mutation.R'))
source(file.path(getwd(), 'R/tests/constants.R'))
source(file.path(getwd(), 'R/tests/define-function.R'))
source(file.path(getwd(), 'R/tests/default-function-arg-test.R'))
source(file.path(getwd(), 'R/tests/test-if.R'))
source(file.path(getwd(), 'R/tests/test-exists.R'))
source(file.path(getwd(), 'R/tests/test-null.R'))
source(file.path(getwd(), 'R/tests/test-pmml-custom-func.R'))
source(file.path(getwd(), 'R/tests/test-colon-operator.R'))

testTransformationForTable()
testDataFrameAccess()
testMutation()
testConstants()
testDefineFunction()
testDefaultFunctionArg()
testIf()
testTransformationForExists()
testTransformationForNull()
testTransformationForPmmlCustomFunc()
testColonOperator()